FORMAT: 1A

# suppliers
API для ведения справочника поставщиков оборудования и их подразделений.

# Group Поставщики
Ресурсы, относящиеся к справочнику поставщиков.

## Отбор поставщиков [/api/v1/items{?search,root_id}]

Операции с возможностью отбора поставщиков/подразделений по различным параметрам.

+ Parameters
    + search (string, `труб`) ...строка, содержащаяся в названии, коде или номере записи
    + root_id (integer, `12`) ...ID записи, среди подразделений которой ведется поиск

### Вывод списка поставщиков [GET]

Возвращает список всех поставщиков и их подразделений - с возможностью отбора по критериям:
- подстроке наименования, краткого наименования или кода поставщика/департамента отдела;
- ID записи, ограничивающий список её подразделениями.

+ Response 200 (application/json)

        {
            "success": true,
            "data": [
                {
                    "id": 12,
                    "name": "Департамент труб и технологического оборудования",
                    "code": null,
                    "active": false,
                    "depth": 1,
                    "parent_id": 1,
                    "divisions": [14, 15, 22]
                },
                {
                    "id": 15,
                    "name": "Отдел трубной продукции",
                    "code": "ТП",
                    "active": true,
                    "depth": 2,
                    "parent_id": 12,
                    "divisions": []
                }
            ]
        }
        
+ Response 404 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение с ID: 12 не найден." }
            ],
            "data": {}
        }

## Список поставщиков/подразделений [/items]

Операции со списком всех поставщиков подразделений.

### Регистрация поставщика [POST]

Добавляет поставщика в список (верний уровень иерархии).

+ Request (application/json)

        {
            "name": "ОАО 'Главпоставка'",
            "code": "ГП",
            "active": false
        }

+ Response 201 (application/json)

        {
            "success": true,
            "messages": [
                { "success": "Поставщик ГП: ОАО 'Главпоставка' добавлен в справочник." }
            ],
            "data": {
                "id": 3,
                "name": "ОАО 'Главпоставка',
                "code": "ГП",
                "active": false,
                "depth": 0,
                "parent": null,
                "divisions": []
            }
        }
        
+ Response 422 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик ГП: ОАО 'Главпоставка' уже зарегистрирован." }
            ],
            "data": {}
        }
        
### Объединение поставщиков [PUT]

Объединяет несколько записей справочника. Объединяемые записи упорядочиваются с учетом иерархии, после чего сохраняется только первая запись,
а прочие удаляются. Перед их удалением все ссылки в базе данных перенаправляются на объединенную запись.

+ Request (application/json)

        {
            "ids": [3, 32, 13]
        }
        
+ Response 200 (application/json)

        {
            "success": true,
            "messages": [
                { "success": "Выбранные записи объединены c ГП: ОАО 'Главпоставка'." }
            ],
            "data": {
                "id": 3,
                "name": "ОАО 'Главпоставка'",
                "code": "ГП",
                "active": false,
                "depth": 0,
                "parent": null,
                "divisions": []
            }
        }
        
+ Response 404 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение с ID: 32 не найден." }
            ],
            "data": {}
        }

+ Response 422 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Ошибка записи в базу данных." }
            ],
            "data": {}
        }

## Поставщик/подразделение [/items/{id}]

Операции с записью из справочника поставщиков/их подразделений.

+ Parameters
    + id (required, integer, `45`) ... ID записи в справочнике поставщиков.

### Просмотр информации о поставщике/подразделении [GET]

Возвращает информацию о поставщике или подразделении, вышестоящем подразделении и списке отделов/подразделений текущей записи.

+ Response 200 (application/json)

        {
            "success": true,
            "data": {
                "id": 45,
                "name": "Департамент АСУ",
                "code": "АСУ",
                "active": false,
                "depth": 1,
                "parent": {
                    "id": 3,
                    "name": "ОАО 'Главпоставка'",
                    "code": "ГП",
                    "active": false
                },
                "divisions": [
                    {
                        "id": 46,
                        "name": "Отдел автоматизированных информационных управленческих систем",
                        "code": "АИУС",
                        "active": true
                    },
                    {
                        "id": 48,
                        "name": "Отдел компьютерных сетей и оборудования",
                        "code": "КСО",
                        "active": true
                    }
                ]
            }
        }

+ Response 404 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение с ID: 45 не найден." }
            ],
            "data": {}
        }

### Редактирование информации о поставщике/подразделении [PATCH]

Сохраняет изменения информации о поставщике.

+ Request (application/json)

        {
            "name": "Отдел труб",
            "code": "ОТ",
            "active": true
        }
        
+ Response 200 (application/json)

        {
            "success": true,
            "message": [
                { "success": "Поставщик/подразделение ОТ: Отдел труб сохранен." }
            ],
            "data": {
                "id": 45,
                "name": "Отдел труб",
                "code": "ОТ",
                "active": true,
                "depth": 3,
                "parent": {
                    "id": 33,
                    "name": "Департамент трубной продукции",
                    "code": null,
                    "active": false
                },
                "divisions": []
            }
        }
        
+ Response 404 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение с ID: 45 не найден." }
            ],
            "data": {}
        }

+ Response 422 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик ОТ: Отдел труб уже зарегистрирован." }
            ],
            "data": {}
        }

### Добавление подразделения/отдела [POST]

Добавляет новое подразделение к текущему поставщику/подразделению.

+ Request (application/json)

        {
            "name": "Отдел труб большого диаметра",
            "code": "ТБД",
            "active": true
        }

+ Response 201 (application/json)

        {
            "success": true,
            "messages": [
                { "success": "Поставщик ТБД: Отдел труб большого диаметра добавлен в справочник." }
            ],
            "data": {
                "id": 47,
                "name": "Отдел труб большого диаметра",
                "code": "ТБД",
                "active": true
                "depth": 3,
                "parent": {
                    "id": 45,
                    "name": "Отдел труб",
                    "code": "ОТ",
                    "active": true
                },
                "divisions": []
            }
        }
        
+ Response 404 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение с ID: 45 не найден." }
            ],
            "data": {}
        }

+ Response 422 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение ТБД: Отдел труб большого диаметра уже зарегистрирован." }
            ],
            "data": {}
        }

### Удаление подразделения/отдела [DELETE]

Удаляет запись о поставщике/подразделении, если на нее нет ссылок в базе данных.

+ Response 200 (application/json)

        {
            "success": true,
            "messages": [
                { "error": "Поставщик/подразделение ОТ: Отдел труб удален." }
            ],
            "data": {
                "id": 45,
                "name": "Отдел труб",
                "code": "ОТ",
                "active": true,
                "depth": 2,
                "parent": {
                    "id": 14,
                    "name": "Департамент трубной продукции",
                    "code": "ДТ",
                    "active": false
                },
                "divisions": []
            }
        }
        
+ Response 404 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение с ID: 45 не найден." }
            ],
            "data": {}
        }

+ Response 422 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Перед удалением поставщика/подразделения ОТ: Отдел труб необходимо удалить все ссылки на запись в базе данных." }
            ],
            "data": {}
        }

### Перенос подразделений в текущую запись [PUT]

Преобразует выбранных поставщиков/подразделения в подразделения текущего поставщика, если он не
является их собственным подразделением.

+ Request

        {
            "ids": [23, 54]
        }
        
+ Response 200 (application/json)

        {
            "success": true,
            "messages": [
                { "error": "Выбранные записи преобразованы в подразделения поставщика ОТ: Отдел труб." }
            ],
            "data": {
                "id": 45,
                "name": "Отдел труб",
                "code": "ОТ",
                "active": true,
                "depth": 2,
                "parent": {
                    "id": 14,
                    "name": "Департамент трубной продукции",
                    "code": "ДТ",
                    "active": false
                },
                "divisions": [
                    {
                        "id": 23,
                        "name": "Отдел труб большого диаметра",
                        "code": "ТБД",
                        "active": true
                    },
                    {
                        "id": 53,
                        "name": "Отдел сварных труб",
                        "code": "ОСД",
                        "active": true
                    },
                    {
                        "id": 54,
                        "name": "Отдел труб малого диаметра",
                        "code": "ТМД",
                        "active": true
                    }
                ]
            }
        }
        
+ Response 404 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Поставщик/подразделение с ID: 45 не найден." }
            ],
            "data": {}
        }

+ Response 422 (application/json)

        {
            "success": false,
            "messages": [
                { "error": "Нельзя перенести поставщика/подразделение ГП: ОАО 'Главпоставка' в состав его собственного подразделения." }
            ],
            "data": {}
        }
